// @ts-nocheck -- skip type checking
import * as d_docs_13 from "../content/docs/guides/common-tasks/streaming-chat.mdx?collection=docs"
import * as d_docs_12 from "../content/docs/guides/common-tasks/rotate-api-keys.mdx?collection=docs"
import * as d_docs_11 from "../content/docs/guides/common-tasks/model-fallback.mdx?collection=docs"
import * as d_docs_10 from "../content/docs/guides/setup-anthropic.mdx?collection=docs"
import * as d_docs_9 from "../content/docs/guides/multi-provider.mdx?collection=docs"
import * as d_docs_8 from "../content/docs/guides/models.mdx?collection=docs"
import * as d_docs_7 from "../content/docs/guides/index.mdx?collection=docs"
import * as d_docs_6 from "../content/docs/guides/anthropic.mdx?collection=docs"
import * as d_docs_5 from "../content/docs/api/models.mdx?collection=docs"
import * as d_docs_4 from "../content/docs/api/index.mdx?collection=docs"
import * as d_docs_3 from "../content/docs/api/chat.mdx?collection=docs"
import * as d_docs_2 from "../content/docs/quickstart.mdx?collection=docs"
import * as d_docs_1 from "../content/docs/index.mdx?collection=docs"
import * as d_docs_0 from "../content/docs/authentication.mdx?collection=docs"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"authentication.mdx","fullPath":"content/docs/authentication.mdx"}, data: d_docs_0 }, { info: {"path":"index.mdx","fullPath":"content/docs/index.mdx"}, data: d_docs_1 }, { info: {"path":"quickstart.mdx","fullPath":"content/docs/quickstart.mdx"}, data: d_docs_2 }, { info: {"path":"api/chat.mdx","fullPath":"content/docs/api/chat.mdx"}, data: d_docs_3 }, { info: {"path":"api/index.mdx","fullPath":"content/docs/api/index.mdx"}, data: d_docs_4 }, { info: {"path":"api/models.mdx","fullPath":"content/docs/api/models.mdx"}, data: d_docs_5 }, { info: {"path":"guides/anthropic.mdx","fullPath":"content/docs/guides/anthropic.mdx"}, data: d_docs_6 }, { info: {"path":"guides/index.mdx","fullPath":"content/docs/guides/index.mdx"}, data: d_docs_7 }, { info: {"path":"guides/models.mdx","fullPath":"content/docs/guides/models.mdx"}, data: d_docs_8 }, { info: {"path":"guides/multi-provider.mdx","fullPath":"content/docs/guides/multi-provider.mdx"}, data: d_docs_9 }, { info: {"path":"guides/setup-anthropic.mdx","fullPath":"content/docs/guides/setup-anthropic.mdx"}, data: d_docs_10 }, { info: {"path":"guides/common-tasks/model-fallback.mdx","fullPath":"content/docs/guides/common-tasks/model-fallback.mdx"}, data: d_docs_11 }, { info: {"path":"guides/common-tasks/rotate-api-keys.mdx","fullPath":"content/docs/guides/common-tasks/rotate-api-keys.mdx"}, data: d_docs_12 }, { info: {"path":"guides/common-tasks/streaming-chat.mdx","fullPath":"content/docs/guides/common-tasks/streaming-chat.mdx"}, data: d_docs_13 }]);
export const meta = _runtime.meta<typeof _source.meta>([{"info":{"path":"meta.json","fullPath":"content/docs/meta.json"},"data":{"title":"Documentation","pages":["index","quickstart","authentication","api/index","api/chat","api/models","guides/index","guides/setup-anthropic","guides/anthropic","guides/models","guides/common-tasks/rotate-api-keys","guides/common-tasks/streaming-chat","guides/common-tasks/model-fallback"]}}, {"info":{"path":"api/meta.json","fullPath":"content/docs/api/meta.json"},"data":{"title":"API Reference","pages":["index","chat","models"]}}, {"info":{"path":"guides/meta.json","fullPath":"content/docs/guides/meta.json"},"data":{"title":"Guides","pages":["index","setup-anthropic","anthropic","models","multi-provider","common-tasks/rotate-api-keys","common-tasks/streaming-chat","common-tasks/model-fallback"]}}]);