// ============================================================================
// SERVER-SIDE USER PROFILE SYNCHRONIZATION
// ============================================================================
// Ensures authenticated users have profiles in the users table
// Call this in API routes after authentication checks

import { SupabaseClient } from '@supabase/supabase-js'

/**
 * Ensures the authenticated user has a profile in the users table
 * This should be called in API routes after verifying authentication
 *
 * @param supabase - Supabase client (should be server client with service role)
 * @param userId - The authenticated user's ID from auth.uid()
 * @returns True if profile exists or was created, false otherwise
 */
export async function ensureUserProfile(
  supabase: SupabaseClient,
  userId: string
): Promise<boolean> {
  try {
    // Check if user profile already exists
    const { data: existingProfile, error: checkError } = await supabase
      .from('users')
      .select('id')
      .eq('id', userId)
      .maybeSingle()

    if (checkError) {
      console.error('[ensureUserProfile] Error checking profile:', checkError)
      return false
    }

    // Profile exists, all good
    if (existingProfile) {
      return true
    }

    console.warn(`[ensureUserProfile] Profile missing for user ${userId}, creating...`)

    // Get user info from auth.users
    const { data: authUser, error: authError } = await supabase.auth.admin.getUserById(
      userId
    )

    if (authError || !authUser.user) {
      console.error('[ensureUserProfile] Could not fetch auth user:', authError)
      return false
    }

    const user = authUser.user

    // Extract user details
    const fullName =
      user.user_metadata?.full_name ||
      user.user_metadata?.name ||
      user.email?.split('@')[0] ||
      'User'

    // Create the profile
    const { error: createError } = await supabase.from('users').insert({
      id: userId,
      email: user.email!,
      full_name: fullName,
      company_name: user.user_metadata?.company_name || null,
      tier: 'free',
      status: 'active',
      role: 'user',
      credits_balance: 0,
      free_requests_balance: 0,
      referral_code: null, // Will be auto-generated by trigger
      referred_by: null,
      created_at: user.created_at,
      updated_at: new Date().toISOString(),
    })

    if (createError) {
      console.error('[ensureUserProfile] Failed to create profile:', createError)
      return false
    }

    console.log(`[ensureUserProfile] Successfully created profile for ${user.email}`)
    return true
  } catch (error) {
    console.error('[ensureUserProfile] Unexpected error:', error)
    return false
  }
}

/**
 * Middleware-style helper for API routes
 * Returns user profile if exists, throws error if not
 *
 * Usage:
 * ```ts
 * const profile = await requireUserProfile(supabase, user.id);
 * if (!profile) {
 *   return NextResponse.json({ error: 'Profile not found' }, { status: 500 });
 * }
 * ```
 */
export async function requireUserProfile(
  supabase: SupabaseClient,
  userId: string
) {
  // Ensure profile exists
  const profileExists = await ensureUserProfile(supabase, userId)

  if (!profileExists) {
    return null
  }

  // Fetch and return the profile
  const { data: profile, error } = await supabase
    .from('users')
    .select('*')
    .eq('id', userId)
    .single()

  if (error) {
    console.error('[requireUserProfile] Error fetching profile:', error)
    return null
  }

  return profile
}
